application: jwplayer-1217
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cron
  script: cron.php
- url: /flash
  script: platform.php #?mediaid=sYKZyjxB&playerid=keStX2EI
- url: /html5
  script: platform.php #?mediaid=sYKZyjxB&playerid=WbTtnKtI
- url: /mp4
  script: platform.php #?mediaid=n1viIetj&playerid=WbTtnKtI
