application: jwplayer-1217
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cron
  script: cron.php
- url: /flash
  script: flash.php
- url: /html5
  script: html5.php

